{{- if .Values.lizToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "liz-test-maze.fullname" . }}-token
  labels:
    {{- include "liz-test-maze.labels" . | nindent 4 }}
type: Opaque
stringData:
  LIZ_TOKEN: {{ .Values.lizToken | quote }}
{{- end }}
